services:
  - type: web
    name: phoenix-quiz-app
    env: static
    buildCommand: |
      # Install Flutter
      git clone https://github.com/flutter/flutter.git -b stable --depth 1
      export PATH="$PATH:`pwd`/flutter/bin"

      # Verify Flutter installation
      flutter --version

      # Get dependencies
      flutter pub get

      # Build for web with optimizations
      flutter build web --release
    staticPublishPath: ./build/web
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
